### ISSUE TITLE
Ignore local.services.yml

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/drupal-vm#18]
Setting up D8 to be nice for front end dev requires something like: https://www.chapterthree.com/blog/drupal-8-theming-setting-up-theme-debugging

So we end up with a `local.settings.yml` file that needs to be git ignored.

**Comment by hawkeyetwolf** [comment]
The official way to do this (for now anyway) is to use `development.services.yml`, which lives in the main `sites` directory (as opposed to the individual site directories). A stub file gets generated automagically during provisioning (by either Composer or Ansible, I can't remember) and is `.gitignore`d. Okay to close this one out @soniktrooth ?

D.o documentation: https://www.drupal.org/node/2598914
